name: 'python-builder'
description: ''
inputs:
  dry-run:
    description: 'do not publish anything'
    required: false
    default: false
runs:
  using: 'node12'
  main: '../../dist/builder/index.js'
