name: build

on:
  push:
    branches:
      - main
      - 'renovate/**'

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        flavor: [focal, bionic]

    env:
      FLAVOR: ${{ matrix.flavor }} # build target, name required by binary-builder

    steps:
      - uses: actions/checkout@v2.3.4

      - name: docker-config
        uses: renovatebot/internal-tools@v1.5.3
        with:
          command: docker-config

      - name: binary-builder
        uses: renovatebot/internal-tools@v1.5.3
        with:
          command: binary-builder
          dry-run: ${{github.ref != 'refs/heads/main'}}
          build-args: FLAVOR
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v2.2.2
        with:
          name: ${{ env.FLAVOR }}
          path: .cache/*.tar.xz
