name: build

on:
  push:
    branches:
      - master
      - 'renovate/**'

  pull_request:

env:
  # https://github.com/chalk/supports-color/issues/106
  FORCE_COLOR: true
  NODE_VERSION: 12

jobs:
  cleanup:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: github-cleanup
        uses: renovatebot/internal-tools@v0
        continue-on-error: true
        with:
          command: github-cleanup
          token: ${{ secrets.GH_TOKEN }}

  build:
    needs: [cleanup]
    runs-on: ubuntu-latest

    # timeout-minutes: 60

    strategy:
      matrix:
        ubuntu_version: [18.04, 20.04]

    env:
      UBUNTU_VERSION: ${{ matrix.ubuntu_version }}

    steps:
      - name: docker-config
        uses: renovatebot/internal-tools@v0
        with:
          command: docker-config

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: actions/checkout@v2

      - name: Prepare
        run: |
          yarn install --frozen-lockfile --link-duplicates

      - name: Build builder
        run: |
          docker buildx build --load -t builder --build-arg UBUNTU_VERSION .

      - name: Build build python
        run: yarn start

      - run: ls -la .cache/

      - uses: actions/upload-artifact@v2
        with:
          name: python
          path: .cache/*.tar.xz
