name: build

on:
  push:
    branches:
      - master
      - 'renovate/**'

  pull_request:

env:
  FLAVOR: focal # build target, name required by binary-builder

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - name: docker-config
        uses: renovatebot/internal-tools@v1.3.3
        with:
          command: docker-config

      - name: binary-builder
        uses: renovatebot/internal-tools@v1.3.3
        with:
          command: binary-builder
          dry-run: ${{github.ref != 'refs/heads/master'}}
          build-args: FLAVOR
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v2.2.2
        with:
          name: ${{ env.FLAVOR }}
          path: .cache/*.tar.xz
